# Volatility models {#v}

## ARCH (Autoregressive Conditional Heteroskedasticity model)

$$\begin{equation*}
    \varepsilon_t=\sigma_t\zeta_t
\end{equation*}$$

- $\zeta_t$: white noise following $N(0,1)$
- $\sigma_t^2$: variance of $\varepsilon_t$:

$$\begin{equation*}
    \sigma_t^2=\alpha_0+\sum_{i=1}^p{\alpha_i\varepsilon_{t-i}^2}
\end{equation*}$$

- $\alpha_0>0, \alpha_i\geq0$

<p>&nbsp;</p>

## GARCH (Generalized Autoregressive Conditional Heteroskedasticity model)

$$\begin{equation*}
    \sigma_t^2=\alpha_0+\sum_{i=1}^p{\alpha_i\varepsilon_{t-i}^2}+\sum_{i=1}^q{\beta_j\sigma_{t-j}^2}
\end{equation*}$$

<!-- <p>&nbsp;</p> -->

### Estimation

- MLE:

$$\begin{equation*}
        l_t(\boldsymbol{\theta},\boldsymbol{\varphi})=-\frac{1}{2}\log{2\pi}-\frac{1}{2}\log{\sigma_t^2}-\frac{\varepsilon_t^2}{2\sigma_t^2}
    \end{equation*}$$
    
- FOC:

\begin{align*}
    \frac{\partial l_t}{\partial\boldsymbol{\theta}}&=\frac{\varepsilon_t\omega_t}{\sigma_t^2}+\frac{\sigma_t^2}{2}\frac{\partial\sigma_t^2}{\partial\boldsymbol{\theta}}\bigg(\frac{\varepsilon_t^2}{\sigma_t^2}-1\bigg)=0 \\
    \frac{\partial l_t}{\partial\boldsymbol{\varphi}}&=\frac{1}{2\sigma_t^2}\frac{\partial\sigma_t^2}{\partial\boldsymbol{\varphi}}\bigg(\frac{\varepsilon_t^2}{\sigma_t^2}-1\bigg)=0
\end{align*}

- Recursive algorithm:

\begin{align*}
    \frac{\partial\sigma_t^2}{\partial\boldsymbol{\theta}}&=\sum_{j=1}^q{\beta_j\frac{\partial\sigma_{t-j}^2}{\partial\boldsymbol{\theta}}}-2\sum_{i=1}^p{\alpha_i\boldsymbol{\omega}_t\varepsilon_{t-i}} \\
    \frac{\partial\sigma_t^2}{\partial\boldsymbol{\varphi}}&=\sum_{j=1}^q{\beta_j\frac{\partial\sigma_{t-j}^2}{\partial\boldsymbol{\varphi}}}+\boldsymbol{\epsilon}_t
\end{align*}