# Order Selection

## Stationarity

- **Covariance/Weak stationarity**

\begin{align*}
    &\text{E}[x_t]=\text{E}[x_{t-s}]=\mu \\
    &\text{Var}[x_t]=\text{Var}[x_{t-s}]=\sigma^2 \\
    &\text{Cov}[x_t,x_{t-s}]=\text{Cov}[x_{t-i},x_{t-i-s}]=\gamma_{t-s}
\end{align*}

- **Strong stationarity** = Weak stationarity + no seasonal trend

- MA(q) models satisfy stationarity, but AR(p) models need restrictions.

- **Lag operator**

$$\begin{equation*}
    L^ix_t\equiv x_{t-i}
\end{equation*}$$

- rewrite AR(p):

\begin{align*}
    &x_t=\alpha_0+\sum_{i=1}^{p}{\alpha_iL^ix_{t-i}}+\varepsilon_t \\
    &x_t=\frac{\varepsilon_t}{1-\sum_{i=1}^{p}{\alpha_iL^i}}=\frac{\varepsilon_t}{\Phi(L)}
\end{align*}

- **Characteristic polynomial**

$$\begin{equation*}
    \Phi(L)=1-\sum_{i=1}^{p}{\alpha_iL^i}=\prod_{i=1}^{p}{(1-\phi_iL)}
\end{equation*}$$

- $x_t \sim$ AR($p$) is stationary $\Leftrightarrow |\frac{1}{\phi_i}|>1$.

<p>&nbsp;</p>

## ADF Test (Augmented Dickey-Fuller Test)

- Intuition: tests the null hypothesis that there exists such a unit root.

\begin{align*}
    x_t&=\cdots+\alpha_{p-2}x_{t-p+2}+\alpha_{p-1}x_{t-p+1}+\alpha_{p}x_{t-p} \\
    &=\cdots+\alpha_{p-2}x_{t-p+2}+\alpha_{p-1}x_{t-p+1}+\alpha_px_{t-p+1}+\alpha_{p}x_{t-p}-\alpha_px_{t-p+1} \\
    &=\cdots+\alpha_{p-2}x_{t-p+2}+(\alpha_{p-1}+\alpha_p)x_{t-p+1}-\alpha_p\Delta x_{t-p+1} \\
    &=\cdots+\alpha_{p-2}x_{t-p+2}+(\alpha_{p-1}+\alpha_p)x_{t-p+2}+(\alpha_{p-1}+\alpha_p)x_{t-p+1}-(\alpha_{p-1}+\alpha_p)x_{t-p+2}-\alpha_p\Delta x_{t-p+1} \\
    &=\cdots-(\alpha_{p-1}+\alpha_p)\Delta x_{t-p+2}-\alpha_p\Delta x_{t-p+1}=\cdots
\end{align*}

- $\Delta x_{t-p+i}=x_{t-p+i}-x_{t-p+i-1}$

- Recursive result:

    $$\begin{equation*}
        \Delta x_t=\alpha_0+\gamma x_{t-1}+\sum_{i=2}^p{c_i\Delta x_{t-i+1}}+\varepsilon_t
    \end{equation*}$$

    - $\gamma=-\bigg(1-\sum_{i=1}^p{\alpha_i}\bigg)$
    - $c_i=\sum_{j=i}^p{\alpha_j}$
    
<p>&nbsp;</p>

## ACF (Autocorrelation Function)

- accounts for both direct and indirect effects of $x_{t-k}$ on $x_t$.

\begin{align*}
    \rho_k&=\text{Corr}[x_{t-k},x_t]\\
    &=\frac{\text{E}[(x_{t-k}-\mu_{t-k})\overline{(x_t-\mu_t)}]}{\sigma_{t-k}\sigma_t}
\end{align*}

<p>&nbsp;</p>

## PACF (Partial Autocorrelation Function)

- accounts for only direct effects of $x_{t-k}$ on $x_t$.

$$\begin{equation*}
    \phi_{ii}=\frac{\rho_i-\sum_{j=1}^{i-1}{\phi_{i-1,j}\rho_{i-j}}}{1-\sum_{j=1}^{i-1}{\phi_{i-1,j}\rho_j}}
\end{equation*}$$

- $j$th order autoregression equation:

$$\begin{equation*}
    x_t-\mu=\sum_{i=1}^j{\phi_{ji}(x_{t-i}-\mu)}+e_t
\end{equation*}$$

- joint coefficients:

$$\begin{equation*}
    \phi_{ij}=\phi_{i-1,j}-\phi_{ii}\phi_{i-1,i-j}
\end{equation*}$$

<p>&nbsp;</p>

## Information Criteria

- Goal: to minimize information loss

**AIC (Akaike IC)**:

$$\begin{equation*}
    \text{AIC}=2k-2\log{\hat{L}}
\end{equation*}$$

**BIC (Bayesian IC)**:

$$\begin{equation*}
    \text{BIC}=k\log{n}-2\log{\hat{L}}
\end{equation*}$$